### ISSUE TITLE
msg: error in repo when updating user password

### ISSUE THREAD

**Issue by appropriatepseudonym** [fortinet-solutions-cse/ansible_fgt_modules#10] opened 2019-04-04 23:43 UTC
Hi, i am getting a 'msg: error in repo' message when i attempt to use the fortios_system_admin module. i can create a user just fine but not change the password of a user that already exists. 

the playbook is as follows:

 `---
- hosts: "{{ host }}"
  gather_facts: no
  vars:
    ansible_python_interpreter: '/home/chad/PycharmProjects/owpcm_new/venv_dev/bin/python'

  tasks:
  - name: Configure admin users.
    fortios_system_admin:
      host:  "{{ host }}"
      username: "{{ operator_user }}"
      password: "{{ operator_pw }}"
      https: True
      system_admin:
        state: "present"
        accprofile: "super_admin"
        name: "{{ srv_user }}"
        password: "{{ srv_pw }}"
    register: fort_admin
    tags:
      - fortigate

`

**Comment by mamunozgonzalez** [comment] 2019-04-05 15:39
Hi @appropriatepseudonym ,
 I can confirm that the playbook is good and your operation is correct. However, our FortiOS REST API prevents from modifying the password of admin accounts: error "Modification of the 'password' field of system.admin is forbidden." (you can see it after running a "diag debug application httpsd -1"). 

Anyway, I find this a bit strange because this operation can be perfectly executed from CLI or GUI, thus I'll be submitting a internal bug report to check if this behaviour can be improved in next FortiOS releases.

Thanks for pointing this out.

**Comment by mamunozgonzalez** [comment] 2019-04-05 15:51
Since the Ansible modules are operating correctly and the problem is located out of the scope of this repo I will close this issue. 

For follow up of the REST API bug please feel free to contact me directly or via your Fortinet Sales representative.

**Closed by mamunozgonzalez** 2019-04-05 15:51 UTC
