### ISSUE TITLE
fortios_firewall_address state=absent is not idempotent

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#8] opened 2019-03-15 10:45 UTC
# Expected

Given a vanilla firewall install, the following playbook *should* return no errors

```
- hosts: localhost
  gather_facts: false
  tasks:
  - fortios_firewall_address:
    host: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom: "{{ vdom }}"
    https: "{{ https }}"
    firewall_address:
      state: "absent"
      name: "ThisObjectDoesNotExist"
```

# Actual result

```
PLAY [localhost] **********************************************************************************************************************************************************************************************************************

TASK [fortios_firewall_address] *******************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 200, "http_method": "DELETE", "http_status": 404, "mkey": "ThisObjectDoesNotExist", "name": "address", "path": "firewall", "revision": "59.0.99.9550766792421668275.1552637972", "serial": "REMOVED", "status": "error", "vdom": "root", "version": "v6.0.3"}, "msg": "Error in repo"}

PLAY RECAP ****************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Logs from the fw (`diagnose debug application httpsd -1`)
```
[httpsd 208 - 1552646445     info] ap_invoke_handler[593] -- new request (handler='logincheck-handler', uri='/logincheck', method='PO
[httpsd 208 - 1552646445     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.21.0
[httpsd 208 - 1552646445     info] ap_invoke_handler[600] -- Source: 192.0.2.1:53905 Destination: 10.10.10.4:443
[httpsd 208 - 1552646445     info] logincheck_handler[305] -- entering vdom for login_attempt (vdom='root')
[httpsd 208 - 1552646445     info] logincheck_handler[399] -- login attempt OK, VDOM updated to 'root'
[httpsd 208 - 1552646445     info] logincheck_handler[407] -- login_attempt (method=5, vdom='root', name='breakglass',admin_name='breakglass', auth_
[httpsd 208 - 1552646445     info] output_response[56] -- sent response (status='1', buf='document.location="/ng/prompt?viewOnly&redir=%2Fng%2F";
')
[httpsd 208 - 1552646445     info] ap_invoke_handler[616] -- request completed (handler='logincheck-handler' result==0)
[httpsd 208 - 1552646445     info] ap_invoke_handler[593] -- new request (handler='api_monitor_v2-handler', uri='/api/v2/monitor/license/status?glob
[httpsd 208 - 1552646445     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.21.0
[httpsd 208 - 1552646445     info] ap_invoke_handler[600] -- Source: 192.0.2.1:53905 Destination: 10.10.10.4:443
[httpsd 208 - 1552646445     info] endpoint_handle_req[616] -- received api_monitor_v2_request from '81.174.248.160'
[httpsd 208 - 1552646445     info] aps_init_process_vdom[1195] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 208 - 1552646445     info] api_store_parameter[227] -- add API parameter 'global': '"1"' (type=string)
[httpsd 208 - 1552646445     info] api_parse_vdom_list[972] -- request is for all VDOMs
[httpsd 208 - 1552646446     info] endpoint_process_req_vdom[457] -- new API request (action='select',path='license',name='status',vdom='root',user=
upd_cfg_extract_av_db_version[312]-version=06000000AVDB00701-00001.00000-1804091807
upd_cfg_extract_avips_engine_version[254]-version=06000000AVEN02800-00006.00012-1805281633
upd_cfg_extract_av_db_version[312]-version=06000000MMDB00101-00067.00065-1903150124
upd_cfg_extract_ids_db_version[371]-version=06000000NIDS02403-00006.00741-1512010230
upd_cfg_extract_avips_engine_version[254]-version=06000000FLEN04300-00004.00025-1809251933
upd_cfg_extract_mudb_version[415]-version=06000000MUDB00103-00002.00183-1901030945
upd_cfg_extract_ids_db_version[371]-version=06000000ISDB00103-00006.00741-1512010230
upd_cfg_extract_ids_db_version[371]-version=06000000APDB00103-00006.00741-1512010230
upd_cfg_extract_ffdb_version[611]-version=06000000FFDB00305-00005.00544-1903141032
upd_cfg_extract_cid_db_version[554]-version=06000000CIDB00000-00001.00074-1901172015
upd_cfg_extract_ibdb_botnet_db_version[457]-version=06000000IBDB00101-00004.00435-1903141000
upd_cfg_extract_dbdb_version[715]-version=06000000DBDB00100-00002.00201-1903141231
upd_cfg_extract_sfas_version[689]-version=06000000SFAS00000-00001.00020-1900071147
upd_cfg_extract_mudb_version[415]-version=06000000MUDB00103-00002.00183-1901030945
[httpsd 208 - 1552646446     info] ap_invoke_handler[616] -- request completed (handler='api_monitor_v2-handler' result==0)
[httpsd 208 - 1552646446     info] ap_invoke_handler[593] -- new request (handler='api_cmdb_v2-handler', uri='/api/v2/cmdb/firewall/address/ThisObje')
[httpsd 208 - 1552646446     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.21.0
[httpsd 208 - 1552646446     info] ap_invoke_handler[600] -- Source: 192.0.2.1:53905 Destination: 10.10.10.4:443
[httpsd 208 - 1552646446     info] api_cmdb_v2_handler[2048] -- received api_cmdb_v2_request from '81.174.248.160'
[httpsd 208 - 1552646446     info] aps_init_process_vdom[1195] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 208 - 1552646446    error] api_parse_json_type[124] -- ignoring unexpected data: 'null'
[httpsd 208 - 1552646446     info] api_store_parameter[227] -- add API parameter 'vdom': '"root"' (type=string)
[httpsd 208 - 1552646446     info] handle_cli_req_v2_vdom[1950] -- new CMDB API request (vdom='root',user='breakglass')
[httpsd 208 - 1552646446     info] api_cmdb_request_init_by_path[1351] -- new CMDB query (path='firewall',name='address')
[httpsd 208 - 1552646446     info] api_cmdb_request_init_by_path[1380] -- querying CMDB entry (mkey='ThisObjectDoesNotExist')
[httpsd 208 - 1552646446     info] api_cmdb_request_init_by_path[1384] -- unable to find 'ThisObjectDoesNotExist' in table 'firewall.address'
[httpsd 208 - 1552646446     info] api_return_cmdb_revision[779] -- ETag check for firewall.address
[httpsd 208 - 1552646446    error] _api_cmdb_obj_missing_error[665] -- Object with mkey ThisObjectDoesNotExist not found. Abort
[httpsd 208 - 1552646446    error] api_return_http_result[631] -- API error 404 raised
[httpsd 208 - 1552646446     info] ap_invoke_handler[616] -- request completed (handler='api_cmdb_v2-handler' result==0)
[httpsd 208 - 1552646446     info] ap_invoke_handler[593] -- new request (handler='logout-handler', uri='/logout', method='POST')
[httpsd 208 - 1552646446     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.21.0
[httpsd 208 - 1552646446     info] ap_invoke_handler[600] -- Source: 192.0.2.1:53905 Destination: 10.10.10.4:443
[httpsd 208 - 1552646446     info] ap_invoke_handler[616] -- request completed (handler='logout-handler' result==0)
```

# Workaround:
Add the following stanza to the play:
`failed_when: false`

**Comment by mamunozgonzalez** [comment] 2019-03-15 10:57
Thanks @JonTheNiceGuy. 
Yes, it is a duplicate of:
https://github.com/fortinet-solutions-cse/ansible_generator/issues/4

**Closed** 2019-03-15 10:57 UTC
